version: '3.1'
services:
  backend:
    build: .
    container_name: app-backend
    depends_on:
        - database
    environment:
      - PG_HOST=database
      - PG_DATABASE=app
      - PG_USER=admin
      - PG_PASSWORD=123456
    ports:
      - "8080:8080"
    links:
      - database
  database:
    image: postgres:11-alpine
    restart: always
    container_name: app-database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
